services:
  - type: web
    name: big-trades-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn polygon_ws_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: WT3I1S4AXdekRj1qHZDD9TyD8Fx5tQjC
