services:
  - type: web
    name: big-trades-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn backend.big_trades_tracker_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: 70D7rupiLla29W4BPvlIr9UGp25_XnuQ
buildCommand: |
  curl https://sh.rustup.rs -sSf | sh -s -- -y
  source $HOME/.cargo/env
  pip install -r requirements.txt
